// Code generated by MockGen. DO NOT EDIT.
// Source: git.haefelfinger.net/piwigo/PiwigoDirectoryUploader/internal/pkg/datastore (interfaces: CategoryProvider)

// Package category is a generated GoMock package.
package category

import (
	datastore "git.haefelfinger.net/piwigo/PiwigoDirectoryUploader/internal/pkg/datastore"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCategoryProvider is a mock of CategoryProvider interface
type MockCategoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryProviderMockRecorder
}

// MockCategoryProviderMockRecorder is the mock recorder for MockCategoryProvider
type MockCategoryProviderMockRecorder struct {
	mock *MockCategoryProvider
}

// NewMockCategoryProvider creates a new mock instance
func NewMockCategoryProvider(ctrl *gomock.Controller) *MockCategoryProvider {
	mock := &MockCategoryProvider{ctrl: ctrl}
	mock.recorder = &MockCategoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCategoryProvider) EXPECT() *MockCategoryProviderMockRecorder {
	return m.recorder
}

// GetCategoryByKey mocks base method
func (m *MockCategoryProvider) GetCategoryByKey(arg0 string) (datastore.CategoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByKey", arg0)
	ret0, _ := ret[0].(datastore.CategoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByKey indicates an expected call of GetCategoryByKey
func (mr *MockCategoryProviderMockRecorder) GetCategoryByKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByKey", reflect.TypeOf((*MockCategoryProvider)(nil).GetCategoryByKey), arg0)
}

// GetCategoryByPiwigoId mocks base method
func (m *MockCategoryProvider) GetCategoryByPiwigoId(arg0 int) (datastore.CategoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByPiwigoId", arg0)
	ret0, _ := ret[0].(datastore.CategoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByPiwigoId indicates an expected call of GetCategoryByPiwigoId
func (mr *MockCategoryProviderMockRecorder) GetCategoryByPiwigoId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByPiwigoId", reflect.TypeOf((*MockCategoryProvider)(nil).GetCategoryByPiwigoId), arg0)
}

// SaveCategory mocks base method
func (m *MockCategoryProvider) SaveCategory(arg0 datastore.CategoryData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCategory", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCategory indicates an expected call of SaveCategory
func (mr *MockCategoryProviderMockRecorder) SaveCategory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCategory", reflect.TypeOf((*MockCategoryProvider)(nil).SaveCategory), arg0)
}
